### ISSUE TITLE
프로젝트 기본 패키지 구조 관련 논의사항

### ISSUE THREAD

**Issue by ksc1008** [KappZzang/Jeongsan-Android#1]
### ⚠️문제점
앞으로 개발을 진행함에 있어서 자주 쓰일 패키지명을 미리 정해두고 통일할 필요성이 있을 것 같습니다.

### 💡해결책
현재 생각중인 프로젝트 패키지 구조는 다음과 같습니다.

루트 패키지: com.kappzzang.jeonsan
- ui
    - activities
      - (개별 액티비티)
    - fragments
      - (개별 프래그먼트)
    - customviews
- domain
  - models
  - repositories
  - usecases
- data
  - entities
  - apis
  - mappers
  - repositoryimpls
  - datasources
- service
- util

다른 의견이 있다면 코멘트 남겨주세요!

### 대안
_해당 없음_

### 참고 사항
- application 클래스는 루트 패키지에 작성
- activities, fragments 패키지 내부에 각 액티비티, 프래그먼트 이름으로 패키지 생성. 
해당 패키지 내부에 adapter, viewmodel, activity, di 등 관련된 클래스 구현

### ✅진행 사항
- [ ] 프로젝트 패키지 구조 결정

**Comment by jsh00325** [comment]
전체적으로 깔끔하고 좋은 구조인 것 같습니다👍. 추가적으로 아래에 몇 가지 의견 남깁니다!

1. 패키지명을 단수형으로 통일하는 것은 어떨까요? 패키지 명을 단수형으로 통일하는 것이 더 명확하고 관리하기 쉽다고 생각합니다. 단수형으로 통일하면 나중에 패키지를 찾거나 관리할 때, 여러 모듈이 있던 없던 간에 일관된 형태여서 더 명확하게 구분할 수 있을 것 같습니다!

2. di 모듈을 따로 만드는 것은 어떻게 생각하시나요? repository에 대한 di도 만들고, usecase에 대한 di도 만드는데 별도로 di라는 패키지를 만들어서 관리하면 편할 것 같다고 생각합니다!

**Comment by cleonno3o** [comment]
1. 저도 좋은 패키지 구조 같습니다! 여기에 수현님 의견처럼 단수로 작명 및 di 모듈을 추가하는 것까지 적용하면 더 좋을 것 같다고 생각해요!

2. ui 내부에 activity, fragment, viewmodel로 구분하는 대신 화면 구성 단위?로 나누는 것도 좋은 것 같아요! (예: 정산목록화면, 그룹생성화면 등) 특정 화면을 구현하거나 수정할때 더 빠르게 접근할 수 있다고 생각해요!

3. 단순 오타이신 것 같지만 루트패키지명은 jeongsan이 되면 될것 같아요!

**Comment by ksc1008** [comment]
> 1. 패키지명을 단수형으로 통일하는 것은 어떨까요? 패키지 명을 단수형으로 통일하는 것이 더 명확하고 관리하기 쉽다고 생각합니다. 단수형으로 통일하면 나중에 패키지를 찾거나 관리할 때, 여러 모듈이 있던 없던 간에 일관된 형태여서 더 명확하게 구분할 수 있을 것 같습니다!
> 2. di 모듈을 따로 만드는 것은 어떻게 생각하시나요? repository에 대한 di도 만들고, usecase에 대한 di도 만드는데 별도로 di라는 패키지를 만들어서 관리하면 편할 것 같다고 생각합니다!

> 2. ui 내부에 activity, fragment, viewmodel로 구분하는 대신 화면 구성 단위?로 나누는 것도 좋은 것 같아요! (예: 정산목록화면, 그룹생성화면 등) 특정 화면을 구현하거나 수정할때 더 빠르게 접근할 수 있다고 생각해요!

일단은 작업할 때 패키지 구조를 다음과 같이 잡도록 하겠습니다!

- ui
    - (개별 페이지 단위)
- domain
  - model
  - repository
  - usecase
- data
  - entity
  - api
  - mapper
  - repositoryimpl
  - datasource
- service
- util
- di

또 다른 의견사항이 있다면 남겨주세요.
